### ISSUE TITLE
Split business logic between stadh runtime and stash.rs in the correct way

### ISSUE THREAD

**Issue by dr-orlovsky** [rgb-org/rgb-node#135]
Both https://github.com/rgb-org/rgb-node/blob/master/src/stashd/stash.rs and https://github.com/rgb-org/rgb-node/blob/master/src/stashd/runtime.rs are parts of stadh daemon, however the difference between this two files is the following:
- Methods from runtime.rs (prefixed with `rpc_`) are called only from the RPC interface. The only thing taht they should do is to process RPC arguments and pass them to the methods from
- stash.rs, which must implement the business logic itself.

Methods from `stash.rs` may be called from outside of the daemon thread and outside of the RPC scope.

Current implementation does not follows this logic and randomly distributes functionality between these two files. This should be fixed.

**Comment by rajarshimaitra** [comment]
To clarify the intended purpose of this issue a little further. Here is the situation of these two files as they stand.

- The only `rpc_` function with added business logic other than simple transmission of request data are, `rpc_consign()`, `rpc_validate()`, `rpc_merge()` and `rpc_forget()`.

- Among them `rpc_forget()` is currently not implemented and as far as I understand, it needs the pruning strategy to be finalized. So nothing to be done here.

- `rpc_consign()` only consists of logic related to the analysis of the requested input data and then it calls `stashd::Runtime::consign()` method which has the rest of the business logic.
https://github.com/rgb-org/rgb-node/blob/89108e01b129c4abc60c33da3d647f63b78f03c7/src/stashd/runtime.rs#L237-L254
So it seems to me, this one is following the required philosophy and nothing to be done in this case.

- `rpc_validate()` has all the business logic inside `runtime.rs` and there is no corresponding `validate()` function is `stash.rs`. 
https://github.com/rgb-org/rgb-node/blob/89108e01b129c4abc60c33da3d647f63b78f03c7/src/stashd/runtime.rs#L259
So I propose we can shift the entire logic to `stash.rs` as a new `validate()` function to conform with the above philosophy.

- `rpc_merge()` is a little weird because it is implemented in both `runtime.rs` and `stash.rs`, and they don't call each other so they are independent. 
https://github.com/rgb-org/rgb-node/blob/89108e01b129c4abc60c33da3d647f63b78f03c7/src/stashd/runtime.rs#L278
https://github.com/rgb-org/rgb-node/blob/89108e01b129c4abc60c33da3d647f63b78f03c7/src/stashd/stash.rs#L200
As far as I can see `merge()` function in `stash.rs` is never used, and only `rpc_merge()` logic is currently being followed. So I propose we can simply replace `merge()` logic with logic from `rpc_merge()` and keep `rpc_merge()` as a request processor to follow the above philosophy.

- All other `rpc_*()` functions are already following the above philosophy, so nothing to be done for them.

I am starting the work as I mentioned above. 

Let me know if I missed anything.
